# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Admin.create!(:email=>"dormusph@gmail.com", :password=>"123456", :password_confirmation=>"123456")

Applicant.create(first_name: 'Lorenzo', last_name:'Bautista', middle_initial: 'A', nickname:'Enzo', gender: 'M', contact_number: '09172837458', landline_number: '555-5565', civil_status: 'Single', email:'lorenzobautista4@gmail.com',stage:'Pending',room_type: "Two-in-a-room Deluxe",address:"lt 5 something st something address city",religion:"Roman Catholic",guardian_email:"jpfelizco4@yahoo.com")
Applicant.create(first_name: 'Kurt', last_name:'Chan', email:'kurtchan@gmail.com',stage:'Pending',room_type: "Two-in-a-room Deluxe", guardian_email: 'kurtchan@gmail.com')
Applicant.create(first_name: 'Hans', last_name:'Cristobal', email:'hanscristobal@gmail.com',stage:'Pending',room_type: "Two-in-a-room Deluxe", guardian_email: 'hanscristobal@gmail.com')
Applicant.create(first_name: 'Bryan', last_name:'Zerrudo', email:'bryanzerrudo@gmail.com',stage:'Pending',room_type: "Two-in-a-room Deluxe", guardian_email: 'bryanzerrudo@gmail.com')
Applicant.create(first_name: 'Sef', last_name:'Remollo', email:'sefremollo@gmail.com',stage:'Pending',room_type: "Four-in-a-room Deluxe", guardian_email: 'sefremollo@gmail.com')
Applicant.create(first_name: 'Patrick', last_name:'Felizco', email:'patrickfelizco@gmail.com',stage:'Pending',room_type: "Two-in-a-room Deluxe", guardian_email: 'patrickfelizco@gmail.com')
Applicant.create(first_name: 'Vaughn', last_name:'Villarico', email:'vaughn.villarico@gmail.com',stage:'Pending',room_type: "Two-in-a-room Premium", guardian_email: 'vaughn.villarico@gmail.com')
Applicant.create(first_name: 'Jacq', last_name:'Hernandez', email:'jacqhernandez@gmail.com',stage:'Pending',room_type: "Four-in-a-room Premium", guardian_email: 'jacqhernandez@gmail.com')

Room.create(room_number: 101,room_type:'Two-in-a-room Deluxe',room_capacity:2,room_price: 5600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 102,room_type:'Two-in-a-room Deluxe',room_capacity:2,room_price: 5600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 103,room_type:'Two-in-a-room Premium',room_capacity:2,room_price: 6600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 104,room_type:'Two-in-a-room Premium',room_capacity:2,room_price: 6600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 105,room_type:'Two-in-a-room Premium',room_capacity:2,room_price: 6600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 106,room_type:'Two-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 107,room_type:'Two-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 108,room_type:'Two-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 201,room_type:'Two-in-a-room Deluxe',room_capacity:2,room_price: 5600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 202,room_type:'Four-in-a-room Deluxe',room_capacity:2,room_price: 5600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 203,room_type:'Two-in-a-room Premium',room_capacity:2,room_price: 6600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 204,room_type:'Two-in-a-room Premium',room_capacity:2,room_price: 6600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 205,room_type:'Four-in-a-room Premium',room_capacity:2,room_price: 6600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 206,room_type:'Two-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 207,room_type:'Two-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 208,room_type:'Two-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)
Room.create(room_number: 208,room_type:'Four-in-a-room Regular',room_capacity:2,room_price: 4600,occupant_count: 0,room_status:'',floor_area:'',bed_count: 2,bathroom_count: 1)

Meal.create(name:'Vegetarian I',breakfast_meal:'Tapsilog',breakfast_drink:'Orange juice',lunch_meal:'Sisig ricebowl',lunch_drink:'Coke Classic',dinner_meal:'Mcdo 2 pc chicken', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'Vegetarian II',breakfast_meal:'English breakfast',breakfast_drink:'Orange juice',lunch_meal:'Pork chop',lunch_drink:'Coke Classic',dinner_meal:'Chowking Lauriat', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'Vegetarian III',breakfast_meal:'Tapsilog',breakfast_drink:'Orange juice',lunch_meal:'Sisig ricebowl',lunch_drink:'Coke Classic',dinner_meal:'Jollibee 2 pc chicken', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'Fil-Food I',breakfast_meal:'Vigan Longganisa',breakfast_drink:'Iced Tea juice',lunch_meal:'Pork chop',lunch_drink:'Coke Classic',dinner_meal:'Sinangag na sinigang', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'Fil-Food II',breakfast_meal:'Tapsilog',breakfast_drink:'Orange juice',lunch_meal:'Sisig ricebowl',lunch_drink:'Coke Classic',dinner_meal:'KFC 2 pc chicken', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'Fil-Food III',breakfast_meal:'Longsilog',breakfast_drink:'Orange juice',lunch_meal:'Pork chop',lunch_drink:'Coke Classic',dinner_meal:'Crispy Pata', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'European Dish',breakfast_meal:'English breakfast',breakfast_drink:'Coffee',lunch_meal:'Pork chop',lunch_drink:'Coke Classic',dinner_meal:'Surf and Turf', dinner_drink:'Iced tea',price:'300.00')
Meal.create(name:'Oriental Box',breakfast_meal:'Steamed Buns',breakfast_drink:'Tea',lunch_meal:'Dumpling Wonton',lunch_drink:'Coke Classic',dinner_meal:'Mozzarella Macaroni', dinner_drink:'Iced tea',price:'300.00')

LaundryItem.create(laundry_item_type: 'Male', description: 'Coat', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Trousers', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Jeans/Maong', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'T-Shirt with Collar', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Shirt Cotton, Polo L/S', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Shirt, Silk Nylon S/S', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Undershirt', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Sock', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Handkerchief', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Pajama (2pcs)', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Bathrobe', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'T-Shirt/Sport Shirt', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Short Pants', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Jacket/Blazer', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Vest', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Jogging Suit (2pcs)', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Boys Clothes (1 Pair)', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Sweater/Sweat Shirt', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Bath Towel', price: 10)
LaundryItem.create(laundry_item_type: 'Male', description: 'Face Towel', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Dress, Cotton Plain', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Dress, Pleated', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Jeans', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Blouse, L/S', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Blouse, S/S', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Skirt, Plain/Mini', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Skirt, Pleated/Long', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Panty', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Braisserre', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Camisole/Sando', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Leggings', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Slip', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Night	Gown, Silk (Party)', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Night	Gown, Cotton', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Jumpsuit', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Girls Dress', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'T-Shirt', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Slacks', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Panty Hose', price: 10)
LaundryItem.create(laundry_item_type: 'Female', description: 'Hand Towel', price: 10)

FoodPlan.create(food_plan_date: '2016-05-15',meal: 'Vegetarian I',applicant_id:1)
FoodPlan.create(food_plan_date: '2016-05-15',meal: 'Vegetarian III',applicant_id:2)
FoodPlan.create(food_plan_date: '2016-05-15',meal: 'Vegetarian II',applicant_id:3)
FoodPlan.create(food_plan_date: '2016-05-15',meal: 'Vegetarian I',applicant_id:4)
FoodPlan.create(food_plan_date: '2016-05-15',meal: 'European Dish',applicant_id:5)
FoodPlan.create(food_plan_date: '2016-05-15',meal: 'European Dish',applicant_id:6)
FoodPlan.create(food_plan_date: '2016-05-15',meal: 'Vegetarian I',applicant_id:7)